apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: localhost:5000/backend:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: PORT
            value: "80"
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            port: 80
            path: /health
          initialDelaySeconds: 5 # Wait 5 seconds for startup
          periodSeconds: 60 # Check every minute